CREATE TABLE patrons (
    patron_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone_number VARCHAR2(15),
    state VARCHAR2(50),
    zip_code VARCHAR2(10),
    date_of_birth DATE,
    registration_date DATE DEFAULT SYSDATE,
    membership_status VARCHAR2(20) DEFAULT 'Active',
    last_visit DATE
);
